### PR TITLE
fix(dotnet): set paths for global tools

### PR DESCRIPTION
**Pull request by dmccaffery**

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07 @tim528 @tiffanywang3 : can I get a review?

**Comment by sjk07** [comment]
@dmccaffery just for my own sanity what caused this change? 

We are checking if dotnet is in use/local/share/... Then set it. If it's in $home/.dotnet then export the dotnet root env var. 

We also always default to the home directory dotnet install if it exists. 

PS. Push your storage branch :kissing_heart:

**Comment by tim528** [comment]
Reviewed good sir, and I give you my stamp of approval

**Comment by dmccaffery** [comment]
@sjk07 : DOTNET_ROOT is used for the new(ish) global tools dependency evaluation, for instance:

```sh
dotnet tool install -g dotnetsay
```

We did not include this on the PATH previously, so global tools would fail. The reason to check for `/usr/local/share/dotnet` is in case someone installs the dotnet runtime as a shared runtime (apt-get, etc). We also evaluate $HOME/.dotnet as this is where our own installation places the runtime.

**Pull request merged**
