### PR TITLE
feat: add support for ssh using smart cards

### PR DESCRIPTION
**Pull request by dmccaffery**
* configure gpg-agent to support ssh
* add support for removing keygrips to switch smart cards
  - useful when multiple smart cards contains the same keys

### CODE REVIEW

**Comment by sjk07** [comment]
@dmccaffery should this and all other features be in the readme? or do we need to figure a better way to document the functionality prompt provides

**Review by sjk07 — APPROVED** [review]

**Comment by patrickserrano** [comment]
@sjk07 @dmccaffery what about moving the feature documentation into a repo wiki? I'm happy to set it up and clean up the readme, assuming I have permissions to create and edit a wiki for the repo.

**Comment by sjk07** [comment]
@patrickserrano I don't see why that wouldn't be a good idea. as long as everything is in markdown we can eventually move it all to GitHub pages and be fancy (if its worth it). 

Create a new issue and we can start creating a structure / deliverables to make this happen.

**Comment by dmccaffery** [comment]
> @patrickserrano I don't see why that wouldn't be a good idea. as long as everything is in markdown we can eventually move it all to GitHub pages and be fancy (if its worth it).
> 
> Create a new issue and we can start creating a structure / deliverables to make this happen.

there is a separate PR (#60) to migrate to GitHub Actions -- once there it becomes insanely easy to publish to GitHub Pages :)

**Pull request merged**
