### PR TITLE
build: rename workflows and replace stalebot

### PR DESCRIPTION
**Pull request by dmccaffery**
* rename workflows to normalise with most open-source projects
* replace stalebot configuration with stale workflow
  - achieves the same result without requiring a third-party integration
* introduce next branch
  - acts as a prerelease branch
  - now the default target for pull requests
  - required to support development for apple silicon, which may take a
    few iterations to get right
  - allows multiple features / fixes to be batched into a prompt release
* cleanup readme
  - correctly identify validated operating systems
  - replace badges for github worflows and next branch

fix(switch-smart-card): ignore missing keygrips

Closes: #68
Related: #66

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07 -- a webhook with circleci caused the status check to still appear despite the build being removed. I fixed it after seeing it in this PR -- it should not appear again.

**Review by patrickserrano — APPROVED** [review]
LTGM

**Comment by dmccaffery** [comment]
> LTGM

Can you approve it? :-D

**Comment by patrickserrano** [comment]
> > LTGM
> 
> Can you approve it? :-D

I did! lol

I think @sjk07 needs to, he's marked as a code owner.

**Comment by dmccaffery** [comment]
> > > LTGM
> 
> > 
> 
> > Can you approve it? :-D
> 
> 
> 
> I did! lol
> 
> 
> 
> I think @sjk07 needs to, he's marked as a code owner.

Ah; codeowners was touched so @sjk07 has to review as well, which is why it's blocked.

**Review by sjk07 — APPROVED** [review]
Woo! Sorry for blocking this.

LGTM!

**Pull request merged**
