### PR TITLE
fix: pushd is not posix compliant

### PR DESCRIPTION
**Pull request by dmccaffery**
* resolve an issue where prompt could fail to install on operating systems where the default shell is not a bash-variant where `pushd` is available
* enable prompt to be installed in WSL 2 (tested in ubuntu) through bootstrap

image

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07 -- the macos build failed due to a network fluke in circle-ci: 
image

It succeeded otherwise. Up to you if you want to requeue.

**Comment by sjk07** [comment]
@dmccaffery the same issue keeps appearing in CI are you sure it's a fluke?

**Comment by dmccaffery** [comment]
Hmm. Possibly not. I cannot reproduce locally; however. It might be something funky with the circle-ci environment.

**Comment by dmccaffery** [comment]
Ultimately the part that is breaking was not modified, so I'm not sure what is going on there.

**Comment by patrickserrano** [comment]
@dmccaffery fwiw, I've been getting the same error locally on macOS:

Screen Shot 2020-05-21 at 11 21 21 AM

**Comment by sjk07** [comment]
@patrickserrano lets create an issue for this

**Comment by dmccaffery** [comment]
Interesting @patrickserrano -- one thing that could cause this is if you set a GH_TOKEN or PROMPT_TOKEN env-var in your profile that is not valid. The token is used to authenticate to GitHub APIs to work around possible issues with rate limiting (if you bang GitHub like crazy in day-to-day activities).

**Comment by dmccaffery** [comment]
```sh
env | grep _TOKEN
```

**Pull request merged**
